### ISSUE TITLE
npm and aurelia cli installation

### ISSUE THREAD

**Issue by clmorales** [aurelia-plugins/aurelia-plugins-jwt-decode#1]
This is is a nice aurelia jwt-decode.  Thanks a lot. 

What I noticed was some missing documentation. 

First the correct npm install is:
npm install aurelia-plugins-jwt-decode --save 
instead of npm install aurelia-jwt-decode --save

Second when using aurelia-cli is important to mention that you should include the dependency in the aurelia.json file

{
    "name": "aurelia-plugins-jwt-decode",
    "path": "../node_modules/aurelia-plugins-jwt-decode/dist/amd",
    "main": "aurelia-plugins-jwt-decode"
 }

**Comment by bartlenaerts** [comment]
Hi @clmorales,

thanks for the compliment!
I've updated the README file with your comments.

Regards,
Bart

**Comment by clmorales** [comment]
Thank you for putting your time into the plugin. Nice work.


Carlos
