### ISSUE TITLE
Error when using JwtDecode in Typescript with -noImplicit

### ISSUE THREAD

**Issue by cluka** [aurelia-plugins/aurelia-plugins-jwt-decode#2]
The problem I get is:
error TS7016: Could not find a declaration file for module 'aurelia-plugins-jwt-decode'.

This is happening because there is no index.d.ts file in the root of the component. There is no index.d.ts file at all.
https://github.com/Microsoft/TypeScript/issues/14379
Can this be fixed please?

**Comment by bartlenaerts** [comment]
The `aurelia-plugins-jwt-decode` has become deprecated. Please use [https://github.com/auth0/jwt-decode](https://github.com/auth0/jwt-decode).
